name: YT-MORPHE
on:
  workflow_dispatch:
    inputs:
      VERSION:
        description: 'Example: 20.45.36'
        required: false
        default: 'New'
      DEVICE:
        description: 'Select device'
        required: false
        default: 'armeabi-v7a'
        type: choice
        options:
          - armeabi-v7a
          - arm64-v8a
          - x86
          - x86_64
      DEV:
        description: 'Tool cli'
        required: false
        default: 'Stable'
        type: choice
        options:
          - Stable
          - Develop
      FEATURE:
        description: 'Turn on/off feature on: [-e "feature"], off: [-d "feature"]'
        required: false
        default: ' '
permissions: write-all
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
jobs:
  build1:
    name: "Buid ${{ inputs.DEVICE }} amoled root"
    if: github.repository == 'chamchamfy/YT' && github.ref == 'refs/heads/Vip'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: See build
        env:
          VERSION: ${{ inputs.VERSION }}
          DEVICE: ${{ inputs.DEVICE }}
          DEV: ${{ inputs.DEV }}
          TYPE: 'true'
          AMOLED: 'true'
          FEATURE: ${{ inputs.FEATURE }}
        run: |
          . .github/install.sh
          . .github/MYT.sh
      - name: Upload File
        uses: softprops/action-gh-release@v2
        with:
          name: YT-MORPHE ${{ env.VER }} ${{ env.Kad }}
          tag_name: M${{ env.V }}${{ env.VER }}
          files: Up/*
          body: "${{ env.BODY }}"
      - name: Upload Json
        uses: softprops/action-gh-release@v2
        with:
          name: Update
          tag_name: Up
          files: Up*.json
          prerelease: true
  build2:
    name: "Buid ${{ inputs.DEVICE }} amoled no-root"
    if: github.repository == 'chamchamfy/YT' && github.ref == 'refs/heads/Vip'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: See build
        env:
          VERSION: ${{ inputs.VERSION }}
          DEVICE: ${{ inputs.DEVICE }}
          DEV: ${{ inputs.DEV }}
          TYPE: 'false'
          AMOLED: 'true'
          FEATURE: ${{ inputs.FEATURE }}
        run: |
          . .github/install.sh
          . .github/MYT.sh
      - name: Upload File
        uses: softprops/action-gh-release@v2
        with:
          name: YT-MORPHE ${{ env.VER }} ${{ env.Kad }}
          tag_name: M${{ env.V }}${{ env.VER }}
          files: Up/*
          body: "${{ env.BODY }}"
