name: YT-EXT
on:
  workflow_dispatch:
    inputs:
      VERSION:
        description: 'Example: 20.05.46'
        required: false
        default: 'New'
      DEVICE:
        description: 'Select device'
        required: false
        default: 'armeabi-v7a'
        type: choice
        options:
          - armeabi-v7a
          - arm64-v8a
          - x86
          - x86_64
      DEV:
        description: 'Tool cli'
        required: false
        default: 'Stable'
        type: choice
        options:
          - Stable
          - Develop
      FEATURE:
        description: 'Turn on/off feature on: [-e "feature"], off: [-d "feature"]'
        required: false
        default: ' '

permissions: write-all

jobs:
  build1:
    name: "Buid ${{ inputs.DEVICE }} amoled root"
    if: github.repository == 'chamchamfy/YT' && github.ref == 'refs/heads/Vip'
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v5
      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: See build
        env:
          VERSION: ${{ inputs.VERSION }}
          DEVICE: ${{ inputs.DEVICE }}
          DEV: ${{ inputs.DEV }}
          TYPE: 'true'
          AMOLED: 'true'
          FEATURE: ${{ inputs.FEATURE }}
        run: |
          # chamchamfy 
          . .github/install.sh
          . .github/XYT.sh
      - name: Upload File
        run: |
          TAG="X${{ env.V }}${{ env.VER }}"
          gh release create "$TAG" --title "YT-EXT ${{ env.VER }} ${{ env.Kad }}" --notes "${{ env.BODY }}" || true
          gh release upload "$TAG" Up/* --clobber
      - name: Upload Json
        run: |
          gh release create "Up" --title "Update" --notes "" --prerelease || true
          gh release upload "Up" Up*.json --clobber

  build2:
    name: "Buid ${{ inputs.DEVICE }} amoled no-root"
    if: github.repository == 'chamchamfy/YT' && github.ref == 'refs/heads/Vip'
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v5
      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: See build
        env:
          VERSION: ${{ inputs.VERSION }}
          DEVICE: ${{ inputs.DEVICE }}
          DEV: ${{ inputs.DEV }}
          TYPE: 'false'
          AMOLED: 'true'
          FEATURE: ${{ inputs.FEATURE }}
        run: |
          # chamchamfy 
          . .github/install.sh
          . .github/XYT.sh
      - name: Upload File
        run: |
          TAG="X${{ env.V }}${{ env.VER }}"
          gh release create "$TAG" --title "YT-EXT ${{ env.VER }} ${{ env.Kad }}" --notes "${{ env.BODY }}" || true
          gh release upload "$TAG" Up/* --clobber